version: '2'
services:
  stillkicking-app:
    image: stillkicking
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stillkicking-postgresql:5432/StillKicking
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  stillkicking-postgresql:
    extends:
      file: postgresql.yml
      service: stillkicking-postgresql
